name: 'DfE-Threagile'
author: pritchyspritch
description: 'Threat model analysis via open-source toolkit Threagile'
inputs:
  model_file: # id of input variable
    description: 'Threat model input file'
    required: false
    default: 'threagile.yaml'
  optional_args:
    description: 'Optional arguments'
    required: false
    default: ''
  output_dir:
    description: 'Output directory for files'
    required: false
    default: 'threagile/output'
  dfe_threagile:
    description: 'Run DfE Azure automation'
    required: false
    default: false
#outputs:
runs:
  using: 'docker'
  image: 'Dockerfile'
