name: 'Threagile'
author: Threagile
description: 'Threat model analysis via open-source toolkit Threagile'
inputs:
  model-file: # id of input variable
    description: 'Threat model input file'
    required: false
    default: 'threagile.yaml'
  optional-args:
    description: 'Optional arguments'
    required: false
    default: ''
  output-dir:
    description: 'Output directory for files'
    required: false
    default: 'threagile/output'
#outputs:
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.model-file }} 
    - ${{ inputs.output-dir }}
    - ${{ inputs.optional-args }}
branding:
  icon: 'box'  
  color: 'blue'
