name: tag-release

on:
  push:
    branches:
      - main
    paths:
      - 'action.yml'
      - 'Dockerfile'
      - 'entrypoint.sh'

jobs:
  release-on-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Extract major tag
        id: extract-major
        run: >
          echo major_tag=$(echo ${{ steps.bump-version.outputs.new_tag }} | cut -d'.' -f1) >> $GITHUB_OUTPUT
    
      - name: Update major tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag --force ${{ steps.extract-major.outputs.major_tag }} ${{ steps.bump-version.outputs.new_tag }}
          git push origin ${{ steps.extract-major.outputs.major_tag }} --force